name: pr

on:
    pull_request:
        branches: [dev, master]

jobs:
    test-build:
        uses: ./.github/workflows/test-build-deploy.yml
        secrets: inherit
        with:
            deploy: false
